### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-1-eshaanmathakari#1]
Hi Eshaan, 

Really great work. No real issues. I do suggest however that you check that the markdown is rendering correctly. There are several instances at the top where there is plain text. You have to add a space after each # for the markdown to render properly. 

Full credit, contingent on you resolving the minor markdown issue. 
-Greg

**Comment by eshaanmathakari** [comment]
Edited and pushed changes for the file
